package io.janstenpickle.controller.kodi

import eu.timepit.refined.types.string.NonEmptyString

object Commands {
  final val Left: NonEmptyString = NonEmptyString("left")
  final val Right: NonEmptyString = NonEmptyString("right")
  final val Up: NonEmptyString = NonEmptyString("up")
  final val Down: NonEmptyString = NonEmptyString("down")
  final val Select: NonEmptyString = NonEmptyString("select")
  final val PlayPause: NonEmptyString = NonEmptyString("playpause")
  final val VolUp: NonEmptyString = NonEmptyString("volumeup")
  final val VolDown: NonEmptyString = NonEmptyString("volumedown")
  final val Mute: NonEmptyString = NonEmptyString("mute")
  final val Back: NonEmptyString = NonEmptyString("back")
  final val Subtitles: NonEmptyString = NonEmptyString("showsubtitles")
  final val SeekForward: NonEmptyString = NonEmptyString("analogseekforward")
  final val SeekBack: NonEmptyString = NonEmptyString("analogseekback")
  final val OSD: NonEmptyString = NonEmptyString("osd")

  final val ScanVideoLibrary: NonEmptyString = NonEmptyString("scan_video_library")

  final val InputCommands: Set[NonEmptyString] = Set(
    Left,
    Right,
    Up,
    Down,
    Select,
    Mute,
    Back,
    Subtitles,
    SeekForward,
    SeekBack,
    OSD,
    NonEmptyString("pageup"),
    NonEmptyString("pagedown"),
    NonEmptyString("highlight"),
    NonEmptyString("parentdir"),
    NonEmptyString("parentfolder"),
    NonEmptyString("menu"),
    NonEmptyString("previousmenu"),
    NonEmptyString("info"),
    NonEmptyString("pause"),
    NonEmptyString("stop"),
    NonEmptyString("skipnext"),
    NonEmptyString("skipprevious"),
    NonEmptyString("fullscreen"),
    NonEmptyString("aspectratio"),
    NonEmptyString("stepforward"),
    NonEmptyString("stepback"),
    NonEmptyString("bigstepforward"),
    NonEmptyString("bigstepback"),
    NonEmptyString("chapterorbigstepforward"),
    NonEmptyString("chapterorbigstepback"),
    NonEmptyString("nextsubtitle"),
    NonEmptyString("cyclesubtitle"),
    NonEmptyString("playerdebug"),
    NonEmptyString("codecinfo"),
    NonEmptyString("playerprocessinfo"),
    NonEmptyString("nextpicture"),
    NonEmptyString("previouspicture"),
    NonEmptyString("zoomout"),
    NonEmptyString("zoomin"),
    NonEmptyString("playlist"),
    NonEmptyString("queue"),
    NonEmptyString("zoomnormal"),
    NonEmptyString("zoomlevel1"),
    NonEmptyString("zoomlevel2"),
    NonEmptyString("zoomlevel3"),
    NonEmptyString("zoomlevel4"),
    NonEmptyString("zoomlevel5"),
    NonEmptyString("zoomlevel6"),
    NonEmptyString("zoomlevel7"),
    NonEmptyString("zoomlevel8"),
    NonEmptyString("zoomlevel9"),
    NonEmptyString("nextcalibration"),
    NonEmptyString("resetcalibration"),
    NonEmptyString("analogmove"),
    NonEmptyString("analogmovex"),
    NonEmptyString("analogmovey"),
    NonEmptyString("rotate"),
    NonEmptyString("rotateccw"),
    NonEmptyString("close"),
    NonEmptyString("subtitledelayminus"),
    NonEmptyString("subtitledelay"),
    NonEmptyString("subtitledelayplus"),
    NonEmptyString("audiodelayminus"),
    NonEmptyString("audiodelay"),
    NonEmptyString("audiodelayplus"),
    NonEmptyString("subtitleshiftup"),
    NonEmptyString("subtitleshiftdown"),
    NonEmptyString("subtitlealign"),
    NonEmptyString("audionextlanguage"),
    NonEmptyString("verticalshiftup"),
    NonEmptyString("verticalshiftdown"),
    NonEmptyString("nextresolution"),
    NonEmptyString("audiotoggledigital"),
    NonEmptyString("number0"),
    NonEmptyString("number1"),
    NonEmptyString("number2"),
    NonEmptyString("number3"),
    NonEmptyString("number4"),
    NonEmptyString("number5"),
    NonEmptyString("number6"),
    NonEmptyString("number7"),
    NonEmptyString("number8"),
    NonEmptyString("number9"),
    NonEmptyString("smallstepback"),
    NonEmptyString("fastforward"),
    NonEmptyString("rewind"),
    NonEmptyString("play"),
    NonEmptyString("switchplayer"),
    NonEmptyString("delete"),
    NonEmptyString("copy"),
    NonEmptyString("move"),
    NonEmptyString("screenshot"),
    NonEmptyString("rename"),
    NonEmptyString("togglewatched"),
    NonEmptyString("scanitem"),
    NonEmptyString("reloadkeymaps"),
    NonEmptyString("backspace"),
    NonEmptyString("scrollup"),
    NonEmptyString("scrolldown"),
    NonEmptyString("analogfastforward"),
    NonEmptyString("analogrewind"),
    NonEmptyString("moveitemup"),
    NonEmptyString("moveitemdown"),
    NonEmptyString("contextmenu"),
    NonEmptyString("shift"),
    NonEmptyString("symbols"),
    NonEmptyString("cursorleft"),
    NonEmptyString("cursorright"),
    NonEmptyString("showtime"),
    NonEmptyString("showpreset"),
    NonEmptyString("nextpreset"),
    NonEmptyString("previouspreset"),
    NonEmptyString("lockpreset"),
    NonEmptyString("randompreset"),
    NonEmptyString("increasevisrating"),
    NonEmptyString("decreasevisrating"),
    NonEmptyString("showvideomenu"),
    NonEmptyString("enter"),
    NonEmptyString("increaserating"),
    NonEmptyString("decreaserating"),
    NonEmptyString("setrating"),
    NonEmptyString("togglefullscreen"),
    NonEmptyString("nextscene"),
    NonEmptyString("previousscene"),
    NonEmptyString("nextletter"),
    NonEmptyString("prevletter"),
    NonEmptyString("jumpsms2"),
    NonEmptyString("jumpsms3"),
    NonEmptyString("jumpsms4"),
    NonEmptyString("jumpsms5"),
    NonEmptyString("jumpsms6"),
    NonEmptyString("jumpsms7"),
    NonEmptyString("jumpsms8"),
    NonEmptyString("jumpsms9"),
    NonEmptyString("filter"),
    NonEmptyString("filterclear"),
    NonEmptyString("filtersms2"),
    NonEmptyString("filtersms3"),
    NonEmptyString("filtersms4"),
    NonEmptyString("filtersms5"),
    NonEmptyString("filtersms6"),
    NonEmptyString("filtersms7"),
    NonEmptyString("filtersms8"),
    NonEmptyString("filtersms9"),
    NonEmptyString("firstpage"),
    NonEmptyString("lastpage"),
    NonEmptyString("guiprofile"),
    NonEmptyString("red"),
    NonEmptyString("green"),
    NonEmptyString("yellow"),
    NonEmptyString("blue"),
    NonEmptyString("increasepar"),
    NonEmptyString("decreasepar"),
    NonEmptyString("volampup"),
    NonEmptyString("volampdown"),
    NonEmptyString("volumeamplification"),
    NonEmptyString("createbookmark"),
    NonEmptyString("createepisodebookmark"),
    NonEmptyString("settingsreset"),
    NonEmptyString("settingslevelchange"),
    NonEmptyString("stereomode"),
    NonEmptyString("nextstereomode"),
    NonEmptyString("previousstereomode"),
    NonEmptyString("togglestereomode"),
    NonEmptyString("stereomodetomono"),
    NonEmptyString("channelup"),
    NonEmptyString("channeldown"),
    NonEmptyString("previouschannelgroup"),
    NonEmptyString("nextchannelgroup"),
    NonEmptyString("playpvr"),
    NonEmptyString("playpvrtv"),
    NonEmptyString("playpvrradio"),
    NonEmptyString("record"),
    NonEmptyString("togglecommskip"),
    NonEmptyString("showtimerrule"),
    NonEmptyString("leftclick"),
    NonEmptyString("rightclick"),
    NonEmptyString("middleclick"),
    NonEmptyString("doubleclick"),
    NonEmptyString("longclick"),
    NonEmptyString("wheelup"),
    NonEmptyString("wheeldown"),
    NonEmptyString("mousedrag"),
    NonEmptyString("mousemove"),
    NonEmptyString("tap"),
    NonEmptyString("longpress"),
    NonEmptyString("pangesture"),
    NonEmptyString("zoomgesture"),
    NonEmptyString("rotategesture"),
    NonEmptyString("swipeleft"),
    NonEmptyString("swiperight"),
    NonEmptyString("swipeup"),
    NonEmptyString("swipedown"),
    NonEmptyString("error")
  )

}
