name: Controller CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Scala
      uses: olafurpg/setup-scala@v5
      with:
        java-version: openjdk@1.13
    - name: npm install, build, and test
      run: |
        cd controller-ui
        npm install
        npm run build --if-present
    - name: docker login
      run: docker login -u janstenpickle -p '${{secrets.DOCKERHUB}}'
    - name: scala build
      run: |
        sbt -Dsbt.coursier.home=~/.sbt/coursier/ '; project api; docker:publish' -J-Xms3G -J-Xmx6G
