name: Controller CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        - name: Set up JDK (Java 11.0.6)
          uses: actions/setup-java@v1
          with:
            java-version: '11.0.7'

        - name: Cache ivy2
          uses: actions/cache@v1
          with:
            path: ~/.ivy2/cache
            key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
            restore-keys: |
              ${{ runner.os }}-ivy2-
              ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

        - name: Cache SBT
          uses: actions/cache@v1
          with:
            path: ~/.sbt
            key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
            restore-keys: |
              ${{ runner.os }}-sbt-
              ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
              ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        cd controller-ui
        npm install
        npm run build --if-present
    - name: docker login
      run: docker login -u janstenpickle -p '${{secrets.DOCKERHUB}}'
    - name: scala build
      run: |
        sbt -Dsbt.coursier.home=~/.sbt/coursier/ '; project api; docker:publishLocal' -J-Xms3G -J-Xmx6G
